"""Runbook builder: enrichment layer for the live operator dashboard.

This module joins the existing Diagnose -> Propose -> Validate
output with catalog metadata, multi-axis ranking factors, simulation
summaries, and 3-field trajectory arrays, into a single runbook
dict the operator's frontend can render.

Why a separate module:
  - twin/propose.py is pure-Python and side-effect free; it doesn't
    know about timestamps, runbook ids, or the in-memory store.
  - live/ws_server.py is HTTP plumbing; it doesn't know about
    Cause.affected_subsystems or ProcedureSpec.description.
  - This module is the seam that knows both sides. The bridge
    (live/twin_bridge.py) builds the proposal; this module enriches
    the proposal with everything the runbook needs.

Categorisation by "when they were generated" (per BIBLE §3.2):
  - pipeline.{stage_1..stage_4}.at_unix: when each stage produced
    its output. The bridge stamps these during the run; this module
    just passes them through.
  - injection.injected_at_unix, detected_at_unix: the operator's
    "when this happened" view.
  - trajectory: generated by stage 4 (Validate); the per-step twin
    state for the 3 canvas fields.
  - footer.generated_at_unix: when this runbook was sealed.
  - approval.{status,required_role,decided_by,decided_at_unix}:
    operator-action metadata; starts PENDING, set by /approve later.

Multi-axis ranking:
  - The propose.py sort is lexicographic on
    (mission_impact, effort_score, reversibility, risk_score) asc.
  - The factors block in each candidate and the rank_key_comparison
    in the winner block are the operator-facing explanation of
    *which axis decided* the comparison.
"""
from __future__ import annotations

import datetime as _dt
import time
from typing import Any, Dict, List, Optional, Tuple

import numpy as np


# Mapping tables mirrored from twin.propose so this module doesn't
# have to import twin at module load (twin pulls in astropy).
_MISSION_IMPACT_SCORE: Dict[str, float] = {
    "none": 0.0,
    "minor": 0.2,
    "major": 0.5,
    "mission-ending": 1.0,
}
_REVERSIBILITY_SCORE: Dict[str, float] = {
    "trivial": 0.0,
    "easy": 0.1,
    "hard": 0.4,
}


# Three state fields the runbook canvas renders. Per BIBLE §3.2
# Milestone 2 trajectory spec: battery_soc, battery_temp_c,
# payload_temp_c. Each is a 1D array of length horizon/dt + 1.
TRAJECTORY_FIELDS: Tuple[str, ...] = (
    "battery_soc",
    "battery_temp_c",
    "payload_temp_c",
)


# Algorithm description surfaced in the runbook so the operator
# can audit the choice ("show me how this was ranked").
RANKING_ALGORITHM_DESCRIPTION: str = (
    "lexicographic on (mission_impact, effort_score, reversibility, "
    "risk_score) ascending; risk_score is the final tie-breaker, "
    "consulted only when the catalog fields are equal."
)


def _now_unix() -> float:
    return time.time()


def _rank_key_for(candidate: Dict[str, Any]) -> Tuple[float, ...]:
    """Compute the multi-axis rank key for one candidate (dict form).

    Mirrors twin.propose._rank_key so this module can run without
    importing twin (the bridge's deferred import contract).
    """
    return (
        _MISSION_IMPACT_SCORE.get(candidate.get("mission_impact", "minor"), 0.5),
        float(candidate.get("effort_score", 0.5)),
        _REVERSIBILITY_SCORE.get(candidate.get("reversibility", "easy"), 0.1),
        float(candidate.get("risk_score", 1.0)),
    )


def _per_axis_comparison(
    winner: Dict[str, Any],
    runner_up: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """Return the per-axis win/loss report for winner vs runner-up.

    Each row says whether the winner was better on that axis and
    whether that axis was the deciding one. Deciding = the first
    axis on which the two differ (lexicographic order).
    """
    rows: List[Tuple[str, float, float, str, str]] = [
        (
            "mission_impact",
            _MISSION_IMPACT_SCORE.get(winner.get("mission_impact", "minor"), 0.5),
            _MISSION_IMPACT_SCORE.get(runner_up.get("mission_impact", "minor"), 0.5),
            f"{winner.get('mission_impact', '?')} "
            f"({_MISSION_IMPACT_SCORE.get(winner.get('mission_impact', 'minor'), 0.5)})",
            f"{runner_up.get('mission_impact', '?')} "
            f"({_MISSION_IMPACT_SCORE.get(runner_up.get('mission_impact', 'minor'), 0.5)})",
        ),
        (
            "effort_score",
            float(winner.get("effort_score", 0.5)),
            float(runner_up.get("effort_score", 0.5)),
            f"{float(winner.get('effort_score', 0.5)):.2f}",
            f"{float(runner_up.get('effort_score', 0.5)):.2f}",
        ),
        (
            "reversibility",
            _REVERSIBILITY_SCORE.get(winner.get("reversibility", "easy"), 0.1),
            _REVERSIBILITY_SCORE.get(runner_up.get("reversibility", "easy"), 0.1),
            f"{winner.get('reversibility', '?')} "
            f"({_REVERSIBILITY_SCORE.get(winner.get('reversibility', 'easy'), 0.1)})",
            f"{runner_up.get('reversibility', '?')} "
            f"({_REVERSIBILITY_SCORE.get(runner_up.get('reversibility', 'easy'), 0.1)})",
        ),
        (
            "risk_score",
            float(winner.get("risk_score", 1.0)),
            float(runner_up.get("risk_score", 1.0)),
            f"{float(winner.get('risk_score', 1.0)):.3f}",
            f"{float(runner_up.get('risk_score', 1.0)):.3f}",
        ),
    ]
    out: List[Dict[str, Any]] = []
    decided = False
    for axis, w_val, r_val, w_disp, r_disp in rows:
        if w_val < r_val:
            winner_better = True
        elif w_val > r_val:
            winner_better = False
        else:
            winner_better = True  # tied on this axis; not a win
        # The first axis where they differ is the deciding one.
        is_deciding = (not decided) and (w_val != r_val)
        if is_deciding:
            decided = True
        out.append({
            "axis": axis,
            "winner": w_disp,
            "runner_up": r_disp,
            "winner_better": winner_better,
            "deciding": is_deciding,
        })
    return out


def _winner_reason(
    winner: Dict[str, Any],
    runner_up: Optional[Dict[str, Any]],
    winner_risk_score: float,
) -> str:
    """Build the human-readable "why this won" explanation.

    If there's no runner-up (single-candidate cause), the explanation
    is a no-op ("only candidate"). Otherwise we describe the rank_key
    comparison and which axis decided.
    """
    if runner_up is None:
        return (
            f"{winner['procedure']} was the only candidate for this "
            f"cause; no ranking comparison was performed."
        )
    cmp_rows = _per_axis_comparison(winner, runner_up)
    deciding_axis = next((r for r in cmp_rows if r["deciding"]), None)
    if deciding_axis is None:
        # Tied on every axis (unlikely but possible for the WAIT-only case).
        return (
            f"{winner['procedure']} was selected (tied with "
            f"{runner_up['procedure']} on every catalog axis; "
            f"risk_score {winner_risk_score:.3f} <= "
            f"{float(runner_up.get('risk_score', 1.0)):.3f})."
        )
    axis = deciding_axis["axis"]
    if axis == "risk_score":
        return (
            f"{winner['procedure']} was selected because the catalog "
            f"fields were tied with {runner_up['procedure']}, so risk_score "
            f"broke the tie at {winner_risk_score:.3f} < "
            f"{float(runner_up.get('risk_score', 1.0)):.3f}. Risk is the "
            f"final tie-breaker, not the primary axis."
        )
    return (
        f"{winner['procedure']} was selected because the lexicographic "
        f"rank decided on {axis} ({deciding_axis['winner']} < "
        f"{deciding_axis['runner_up']}). Other axes also favored the "
        f"winner; the lower risk_score of the runner-up "
        f"({float(runner_up.get('risk_score', 1.0)):.3f} < "
        f"{winner_risk_score:.3f}) was never consulted. Risk is the "
        f"final tie-breaker, not the primary axis."
    )


def _loser_rejected_because(
    winner: Dict[str, Any],
    loser: Dict[str, Any],
) -> str:
    """Build the per-loser "rejected because" explanation."""
    cmp_rows = _per_axis_comparison(winner, loser)
    deciding = next((r for r in cmp_rows if r["deciding"]), None)
    if deciding is None:
        return (
            f"tied on every catalog axis with the winner; "
            f"risk_score {float(loser.get('risk_score', 1.0)):.3f} "
            f">= {float(winner.get('risk_score', 1.0)):.3f}"
        )
    axis = deciding["axis"]
    return (
        f"lexicographic rank: {axis} {deciding['runner_up']} > "
        f"{deciding['winner']} (deciding on {axis}; "
        f"{'risk_score not consulted' if axis != 'risk_score' else 'risk_score tie-breaker'})"
    )


def _enrich_candidate(
    candidate: Dict[str, Any],
    *,
    selected: bool,
    winner: Dict[str, Any],
    runner_up: Optional[Dict[str, Any]],
    rank: int = 0,
) -> Dict[str, Any]:
    """Add catalog metadata + factor breakdown to one candidate dict.

    The catalog metadata (description, risk_class, approval_required)
    is passed in via `candidate["_spec"]` by the bridge; this
    function copies the operator-facing fields up to the top level
    and strips the internal marker.
    """
    spec = candidate.get("_spec") or {}
    base = {
        "rank": rank,
        "procedure": candidate["procedure"],
        "risk_score": float(candidate.get("risk_score", 0.0)),
        "effort_score": float(candidate.get("effort_score", spec.get("effort_score", 0.5))),
        "mission_impact": candidate.get("mission_impact", spec.get("mission_impact", "minor")),
        "reversibility": candidate.get("reversibility", spec.get("reversibility", "easy")),
        "description": spec.get("description", ""),
        "risk_class": spec.get("risk_class", "low"),
        "approval_required": spec.get("approval_required", "operator"),
        "rank_key": {
            "mission_impact_score": _MISSION_IMPACT_SCORE.get(
                candidate.get("mission_impact", spec.get("mission_impact", "minor")), 0.5
            ),
            "effort_score": float(candidate.get("effort_score", spec.get("effort_score", 0.5))),
            "reversibility_score": _REVERSIBILITY_SCORE.get(
                candidate.get("reversibility", spec.get("reversibility", "easy")), 0.1
            ),
            "risk_score": float(candidate.get("risk_score", 0.0)),
        },
        "factors": {
            "selected": selected,
            "rejected_because": (
                None if selected
                else _loser_rejected_because(winner, candidate)
            ),
        },
    }
    return base


def _trajectory_payload(
    predicted: Optional[Dict[str, np.ndarray]],
    baseline: Optional[Dict[str, np.ndarray]],
    horizon_s: float,
    dt_s: float,
) -> Dict[str, Any]:
    """Build the trajectory block for the runbook canvas.

    The arrays are numpy 1D; .tolist() for JSON. t_s is shared
    across baseline + predicted; both series have the same length.
    Falls back to a single t_s=[0] entry if predicted is missing
    (caller's contract: validation always produces both).
    """
    if predicted is None and baseline is None:
        return {
            "t_s": [0.0],
            "battery_soc": {"baseline": [], "predicted": []},
            "battery_temp_c": {"baseline": [], "predicted": []},
            "payload_temp_c": {"baseline": [], "predicted": []},
            "horizon_s": float(horizon_s),
            "dt_s": float(dt_s),
        }
    src = predicted if predicted is not None else baseline
    n = len(next(iter(src.values())))
    t_s = [i * float(dt_s) for i in range(n)]
    out: Dict[str, Any] = {
        "t_s": t_s,
        "horizon_s": float(horizon_s),
        "dt_s": float(dt_s),
    }
    for field in TRAJECTORY_FIELDS:
        base_arr = baseline.get(field) if baseline else None
        pred_arr = predicted.get(field) if predicted else None
        out[field] = {
            "baseline": base_arr.tolist() if base_arr is not None else [],
            "predicted": pred_arr.tolist() if pred_arr is not None else [],
        }
    return out


def build_runbook(
    *,
    fault_id: str,
    fault_type: str,
    injection: Dict[str, Any],
    pipeline_timestamps: Dict[str, float],
    proposal_dict: Dict[str, Any],
    cause_catalog: Dict[str, Any],
    candidates_considered: List[Dict[str, Any]],
    symptom_window: List[Dict[str, Any]],
    predicted_trajectory: Optional[Dict[str, np.ndarray]] = None,
    baseline_trajectory: Optional[Dict[str, np.ndarray]] = None,
    horizon_s: float = 3600.0,
    dt_s: float = 120.0,
    primary_subsystem: Optional[str] = None,
    channel: Optional[str] = None,
) -> Dict[str, Any]:
    """Build the full runbook payload from the pipeline output.

    Args:
        fault_id: the FaultScheduler-injected id (e.g. "F-003").
        fault_type: the twin fault_type (e.g. "thermal_heater_stuck_on").
        injection: {kind, channel, magnitude, horizon_s, dt_s,
                    injected_at_unix} from /inject_twin_fault.
        pipeline_timestamps: {stage_1..stage_4 at_unix} from the bridge.
        proposal_dict: the result of proposal.to_dict() (Phase 1).
        cause_catalog: {affected_subsystems, expected_channels} from
                       Cause.affected_subsystems() / expected_channels().
        candidates_considered: every Procedure the cause maps to,
                       with catalog fields attached under `_spec`. The
                       simulated subset carries risk_score; the
                       pre-filtered subset has risk_score=None.
        symptom_window: the bridge's SymptomEvent list as plain dicts.
        predicted_trajectory: optional ValidationResult.predicted_trajectory.
        baseline_trajectory: optional ValidationResult.baseline_trajectory.
        horizon_s, dt_s: validation horizon (for t_s grid).
        primary_subsystem: derived from cause.affected_subsystems()[0]
                          when not provided.
        channel: the channel the operator injected on (e.g. "T-1").

    Returns:
        JSON-serializable dict matching the runbook payload contract.
        The runbook_id is filled in by the store after this returns.
    """
    cause_id = proposal_dict.get("cause", "no_fault_detected")
    cause_score = float(proposal_dict.get("cause_score", 0.0))
    winner_proc = proposal_dict.get("procedure")
    winner_risk = float(proposal_dict.get("risk_score", 0.0))
    ranked = proposal_dict.get("candidates_ranked", []) or []

    # Build a lookup from procedure name -> spec from the
    # candidates_considered list. The bridge attaches `_spec` per
    # candidate; the simulated subset also gets it from
    # candidates_ranked (which the bridge enriches with the same
    # `_spec` field). We merge so the simulated set inherits the
    # spec attached by the bridge.
    spec_by_proc: Dict[str, Dict[str, Any]] = {}
    for c in candidates_considered:
        if c.get("_spec"):
            spec_by_proc[c["procedure"]] = c["_spec"]
    for c in ranked:
        if c.get("_spec") and c["procedure"] not in spec_by_proc:
            spec_by_proc[c["procedure"]] = c["_spec"]

    # The simulated set: candidates in candidates_ranked (or all
    # candidates_considered if ranked is empty — happens for
    # NO_FAULT_DETECTED). The pre-filtered set: candidates in
    # candidates_considered that are not in the simulated set.
    simulated_names = {c.get("procedure") for c in ranked} if ranked else set()
    if not simulated_names:
        # NO_FAULT_DETECTED path: there are no simulated procedures;
        # mark everything as not simulated.
        simulated_names = set()

    candidates_considered_detail: List[Dict[str, Any]] = []
    # Build a risk lookup from the simulated set so candidates_considered
    # entries that don't carry risk_score still get it.
    risk_by_proc: Dict[str, float] = {
        c.get("procedure"): float(c.get("risk_score", 0.0))
        for c in ranked
        if "risk_score" in c
    }
    for c in candidates_considered:
        proc = c.get("procedure")
        spec = spec_by_proc.get(proc, {})
        simulated = proc in simulated_names
        if simulated:
            # Prefer the risk_score from the candidates_considered entry
            # (bridge attaches it for simulated ones); fall back to the
            # ranked lookup. If neither has it, leave as None.
            if "risk_score" in c:
                risk_score = float(c["risk_score"])
            elif proc in risk_by_proc:
                risk_score = risk_by_proc[proc]
            else:
                risk_score = None
        else:
            risk_score = None
        candidates_considered_detail.append({
            "procedure": proc,
            "effort_score": float(c.get("effort_score", spec.get("effort_score", 0.5))),
            "mission_impact": c.get("mission_impact", spec.get("mission_impact", "minor")),
            "reversibility": c.get("reversibility", spec.get("reversibility", "easy")),
            "simulated": simulated,
            "risk_score": risk_score,
            "drop_reason": (
                None if simulated else "coarse_rank above top-K"
            ),
        })

    # The winner (first in ranked) + runner-up (second in ranked).
    winner_dict = ranked[0] if ranked else None
    runner_up_dict = ranked[1] if len(ranked) > 1 else None

    # Enrich the simulated candidates with catalog + factor breakdown.
    enriched_ranked: List[Dict[str, Any]] = []
    for i, c in enumerate(ranked):
        # Reuse the spec from spec_by_proc if present.
        if c.get("procedure") in spec_by_proc and "_spec" not in c:
            c = {**c, "_spec": spec_by_proc[c["procedure"]]}
        is_winner = (i == 0) and (c.get("procedure") == winner_proc)
        # winner_dict/runner_up_dict are the basis for "factors"
        # comparisons. Use the original candidate dicts from ranked
        # so we read effort_score/mission_impact/reversibility.
        enriched_ranked.append(_enrich_candidate(
            c,
            selected=is_winner,
            winner=winner_dict if winner_dict else c,
            runner_up=runner_up_dict,
            rank=i + 1,
        ))

    # Winner block: algorithm + factors + reason.
    winner_block: Dict[str, Any] = {
        "procedure": winner_proc,
        "risk_score": winner_risk,
        "ranking_algorithm": RANKING_ALGORITHM_DESCRIPTION,
        "factors": {},
    }
    if winner_dict is not None:
        winner_block["factors"] = {
            "lowest_risk_score": (
                winner_risk == min(
                    float(c.get("risk_score", 1.0)) for c in ranked
                )
            ),
            "rank_key_comparison": (
                _per_axis_comparison(winner_dict, runner_up_dict)
                if runner_up_dict is not None
                else []
            ),
            "reason": _winner_reason(
                winner_dict, runner_up_dict, winner_risk
            ),
        }

    # Cause block.
    cause_block = {
        "id": cause_id,
        "score": cause_score,
        "affected_subsystems": list(cause_catalog.get("affected_subsystems", []) or []),
        "expected_channels": list(cause_catalog.get("expected_channels", []) or []),
    }

    # Pipeline timestamps: per-stage "at_unix" plus the data each
    # stage produced (kept brief; the frontend re-fetches detail).
    pipeline_block: Dict[str, Any] = {}
    stage_1 = pipeline_timestamps.get("stage_1_at_unix")
    stage_2 = pipeline_timestamps.get("stage_2_at_unix")
    stage_3 = pipeline_timestamps.get("stage_3_at_unix")
    stage_4 = pipeline_timestamps.get("stage_4_at_unix")
    if stage_1 is not None:
        pipeline_block["stage_1_detect"] = {"at_unix": float(stage_1)}
    if stage_2 is not None:
        pipeline_block["stage_2_diagnose"] = {
            "at_unix": float(stage_2),
            "candidate_set_size": len(candidates_considered),
        }
    if stage_3 is not None:
        pipeline_block["stage_3_propose"] = {
            "at_unix": float(stage_3),
            "top_k": len(ranked),
            "considered": len(candidates_considered),
            "ranked": len(ranked),
        }
    if stage_4 is not None:
        pipeline_block["stage_4_validate"] = {"at_unix": float(stage_4)}

    # Subsystem: the first affected subsystem of the cause (the
    # operator's primary lens). The bridge may pass this in
    # explicitly when channel_hint is set; otherwise we infer.
    sub = primary_subsystem
    if not sub:
        subs = cause_block["affected_subsystems"]
        sub = subs[0] if subs else "unknown"

    # Approval block: starts PENDING. The operator clicks Approve /
    # Reject in the frontend; the runbook PATCH endpoint will fill
    # these in (Phase 2+).
    approval_block = {
        "status": "PENDING",
        "required_role": (
            enriched_ranked[0].get("approval_required", "operator")
            if enriched_ranked else "operator"
        ),
        "decided_by": None,
        "decided_at_unix": None,
    }

    # Footer: fault_id, generated_at, twin_digest (Phase 3 stub).
    generated_at = _now_unix()
    footer_block = {
        "fault_id": fault_id,
        "generated_at_unix": generated_at,
        "twin_digest": "(Phase 3: Merkle chain)",
        "runbook_id_legacy": "(Phase 3)",
    }

    return {
        # runbook_id is set by the store after add() returns the id.
        "runbook_id": None,  # placeholder; store overwrites
        "fault_id": fault_id,
        "fault_type": fault_type,
        "injection": {
            "kind": injection.get("kind"),
            "channel": injection.get("channel"),
            "magnitude": injection.get("magnitude"),
            "horizon_s": float(injection.get("horizon_s", horizon_s)),
            "dt_s": float(injection.get("dt_s", dt_s)),
            "injected_at_unix": float(injection.get("injected_at_unix", generated_at)),
        },
        "detected_at_unix": float(injection.get("detected_at_unix", generated_at)),
        "pipeline": pipeline_block,
        "cause": cause_block,
        "subsystem": sub,
        "channel": channel,
        "candidates_considered_detail": candidates_considered_detail,
        "candidates_ranked": enriched_ranked,
        "winner": winner_block,
        "verdict": proposal_dict.get("verdict", {}),
        "symptom_window": list(symptom_window or []),
        "trajectory": _trajectory_payload(
            predicted_trajectory, baseline_trajectory, horizon_s, dt_s,
        ),
        "approval": approval_block,
        "footer": footer_block,
    }


def summary_view(runbook: Dict[str, Any]) -> Dict[str, Any]:
    """Project a runbook to the lightweight shape used by /api/runbooks.

    The list view (dashboard's recent runbooks) doesn't need the
    trajectory arrays, the symptom window, or the per-candidate
    detail; it needs the metadata the operator uses to pick a
    runbook to open.
    """
    return {
        "runbook_id": runbook.get("runbook_id"),
        "fault_id": runbook.get("fault_id"),
        "fault_type": runbook.get("fault_type"),
        "channel": runbook.get("channel"),
        "cause": runbook.get("cause", {}).get("id"),
        "cause_score": runbook.get("cause", {}).get("score"),
        "subsystem": runbook.get("subsystem"),
        "winner": runbook.get("winner", {}).get("procedure"),
        "winner_risk_score": runbook.get("winner", {}).get("risk_score"),
        "verdict_status": runbook.get("verdict", {}).get("status"),
        "approval_status": runbook.get("approval", {}).get("status"),
        "generated_at_unix": runbook.get("footer", {}).get("generated_at_unix"),
    }


def trajectory_view(runbook: Dict[str, Any]) -> Dict[str, Any]:
    """Project a runbook to the trajectory-only shape used by
    /api/runbooks/{id}/trajectory."""
    return runbook.get("trajectory", {})
